# Generated by Django 3.2 on 2021-04-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NintendoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=50)),
                ('character_level', models.IntegerField()),
                ('character_description', models.TextField(blank=True, max_length=200, null=True)),
                ('character_year', models.DateField()),
                ('character_game', models.CharField(max_length=50)),
            ],
        ),
    ]
